
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-06
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-06
pull_requests: [{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"ac-placeholder_for_creating_reviews","number":30,"title":"Ac placeholder for creating reviews","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/30"},{"author":{"id":"MDQ6VXNlcjM1MTE2OTc0","is_bot":false,"login":"sanjana-jilla-913","name":"Sanjana Jilla"},"headRefName":"sj-ReviewTable","number":29,"title":"SJ - Implemented a Review Table","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/29"}]
