
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-dining-s25-06
owner: ucsb-cs156-s25
repo_name: proj-dining-s25-06
pull_requests: [{"author":{"id":"MDQ6VXNlcjU2NDU3OTc1","is_bot":false,"login":"RiyaGupta1234","name":"Riya Gupta"},"headRefName":"riya-addModRoleBackend-v2","number":48,"title":"rg - add moderator role backend VER2","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/48"},{"author":{"id":"U_kgDOCMRpJg","is_bot":false,"login":"saeed-ar","name":""},"headRefName":"sa-update_react_7part2","number":47,"title":"updated to version react router 7","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/47"},{"author":{"id":"U_kgDOBXu1PQ","is_bot":false,"login":"aryanchopra1802","name":""},"headRefName":"ac-form-for-review","number":46,"title":"Aryan - form for creating review ","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/46"},{"author":{"id":"U_kgDOCMRpJg","is_bot":false,"login":"saeed-ar","name":""},"headRefName":"sa-averagescore","number":45,"title":"Sa averagescore","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/45"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-mod-page","number":43,"title":"yl - moderator page","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/43"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-refresh-table","number":42,"title":"yl - FEATURE: refresh table","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/42"},{"author":{"id":"MDQ6VXNlcjY2ODQ5Nzc3","is_bot":false,"login":"yarwinliu","name":""},"headRefName":"yl-alias-approve-table","number":40,"title":"yl - Add moderator table (proposedAlias, approve, reject)","url":"https://github.com/ucsb-cs156-s25/proj-dining-s25-06/pull/40"}]
